In [1]:
import torch
import torch.nn as nn
import torch
import torch.optim as optim

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

#Progress bar
from tqdm import tqdm


#For reading CSV and for math
import numpy as np
import pandas as pd

#Visualize some datasets
import matplotlib.pyplot as plt

#Check our work directory
import os
import shutil


In [2]:
photo_folder_path = r'train\train'
csv_file_path = r'train.csv'

In [3]:
df = pd.read_csv(csv_file_path)

In [4]:
train_blur = df[df["blur"]==1]
train_sharp = df[df["blur"]==0]

print("blur images:", len(train_blur))
print("sharp images:", len(train_sharp))

blur images: 1297
sharp images: 1367


In [5]:
train_val_split = 0.8  # 80% of the photos will be used for training, the rest will be used for validation

In [6]:
dataset_folder_path = r"Dataset"

In [7]:
import random

if not os.path.exists(dataset_folder_path):

    if not os.path.exists(os.path.join(dataset_folder_path, 'train', 'blur')):
        os.makedirs(os.path.join(dataset_folder_path, 'train', 'blur'))
    if not os.path.exists(os.path.join(dataset_folder_path, 'train', 'not_blur')):
        os.makedirs(os.path.join(dataset_folder_path, 'train', 'not_blur'))
    if not os.path.exists(os.path.join(dataset_folder_path, 'valid', 'blur')):
        os.makedirs(os.path.join(dataset_folder_path, 'valid', 'blur'))
    if not os.path.exists(os.path.join(dataset_folder_path, 'valid', 'not_blur')):
        os.makedirs(os.path.join(dataset_folder_path, 'valid', 'not_blur'))

    for _, row in df.iterrows():
        filename = row['filename']
        blur = row['blur']
        file_path = os.path.join(photo_folder_path, filename)
        if blur:
            # copy the file to the "train" folder 80% of the time and to the "valid" folder 20% of the time
            if random.random() < train_val_split:
                shutil.copy(file_path, os.path.join(dataset_folder_path, 'train', "blur"))
            else:
                shutil.copy(file_path, os.path.join(dataset_folder_path, 'valid', "blur"))
        else:
            # copy the file to the "train" folder 80% of the time and to the "valid" folder 20% of the time
            if random.random() < train_val_split:
                shutil.copy(file_path, os.path.join(dataset_folder_path, 'train', "not_blur"))
            else:
                shutil.copy(file_path, os.path.join(dataset_folder_path, 'valid', "not_blur"))


In [8]:
LR = 0.001 * 2
BATCH_SIZE = 4
EPOCHS = 10

# BEST PARAMS
#LR = 0.001
#EPOCHS = 15

In [9]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))]
)

In [10]:
train_dir = 'Dataset/train'
val_dir = 'Dataset/valid'

In [11]:
train_folder = datasets.ImageFolder(root=train_dir, transform=transform)
val_folder = datasets.ImageFolder(root=val_dir,transform=transform)

In [12]:
train_folder.classes

['blur', 'not_blur']

In [13]:
train_loader = DataLoader(train_folder,
                          batch_size=BATCH_SIZE,
                          shuffle=True)
val_loader = DataLoader(val_folder,
                          batch_size=BATCH_SIZE,
                          shuffle=True)

In [14]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        # input [3, 640, 640]
        self.cnn = nn.Sequential(
            nn.Conv2d(in_channels = 3, out_channels = 64, kernel_size = 3, stride = 1, padding = 1),  # [64, 640, 640]
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size = 2, stride = 2, padding = 0),      # [64, 320, 320]

            nn.Conv2d(in_channels = 64, out_channels = 128, kernel_size = 3, stride = 1, padding = 1), # [128, 320, 320]
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size = 2, stride = 2, padding = 0),      # [128, 160, 160]

            nn.Conv2d(in_channels = 128, out_channels = 256, kernel_size = 3, stride = 1, padding = 1), # [256, 160, 160]
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size = 2, stride = 2, padding = 0),      # [256, 80, 80]

            nn.Conv2d(in_channels = 256, out_channels = 512, kernel_size = 3, stride = 1, padding = 1), # [512, 80, 80]
            nn.BatchNorm2d(512),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size = 2, stride = 2, padding = 0),       # [512, 40, 40]
            
            nn.Conv2d(in_channels = 512, out_channels = 512, kernel_size = 3, stride = 1, padding = 1), # [512, 40, 40]
            nn.BatchNorm2d(512),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size = 2, stride = 2, padding = 0),       # [512, 20, 20]
        )
        self.fc = nn.Sequential(
            nn.Linear(in_features = 512*20*20, out_features = 1024),
            nn.ReLU(),
            nn.Linear(in_features = 1024, out_features = 512),
            nn.ReLU(),
            nn.Linear(in_features = 512, out_features = 128), 
            nn.ReLU(), 
            nn.Linear(in_features = 128, out_features = 2)
        )

    def forward(self, x):
        out = self.cnn(x)
        out = out.view(out.size()[0], -1)
        return self.fc(out)
net = Net()

In [15]:
for p in net.parameters():
    print(p.shape)

torch.Size([64, 3, 3, 3])
torch.Size([64])
torch.Size([64])
torch.Size([64])
torch.Size([128, 64, 3, 3])
torch.Size([128])
torch.Size([128])
torch.Size([128])
torch.Size([256, 128, 3, 3])
torch.Size([256])
torch.Size([256])
torch.Size([256])
torch.Size([512, 256, 3, 3])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([512, 512, 3, 3])
torch.Size([512])
torch.Size([512])
torch.Size([512])
torch.Size([1024, 204800])
torch.Size([1024])
torch.Size([512, 1024])
torch.Size([512])
torch.Size([128, 512])
torch.Size([128])
torch.Size([2, 128])
torch.Size([2])


In [16]:
device = torch.device('cuda' if torch.cuda.is_available() else "cpu")
print('Using: ',device)
net.to(device)

Using:  cuda


Net(
  (cnn): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (5): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU()
    (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (8): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (10): ReLU()
    (11): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (12): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (14

In [17]:
print("total allocated memory on gpu (pytorch):", torch.cuda.memory.memory_allocated(device))

total allocated memory on gpu (pytorch): 856899072


In [18]:
# Cross Entropy Loss  
error = nn.CrossEntropyLoss()

#Adam optimizer
optimizer = optim.Adam(net.parameters(), lr = LR)

In [20]:
from sklearn.metrics import roc_auc_score

for epoch in range(EPOCHS):
    train_metric = np.array([])
    val_metric = np.array([])
    train_loss = np.array([])
    val_loss = np.array([])

    loop = tqdm(train_loader, leave=True)
    net.train()
    for batch in loop:
        optimizer.zero_grad()
        inputs = batch[0].to(device)
        labels = batch[1].to(device)
        y_pred = net(inputs)

        loss = error(y_pred,labels.long())
        loss.backward()

        loop.set_description(f"Epoch {epoch+1}")
        optimizer.step()
        try:
            auc = roc_auc_score(labels.cpu().numpy(), np.argmax(y_pred.cpu().data.numpy(), axis=1))     # use AUC-ROC metric if different class are represented
            train_metric = np.append(train_metric, auc)
        except:
            train_metric = np.append(train_metric, np.sum(np.argmax(y_pred.cpu().data.numpy(),axis=1) == labels.cpu().numpy()) / BATCH_SIZE)        # else use Accuracy metric
        train_loss = np.append(train_loss, loss.item())
        loop.set_postfix(loss=np.mean(train_loss), AUC_ROC=np.mean(train_metric))
    net.eval()
    with torch.no_grad():
        loop = tqdm(val_loader, leave=True)
        for batch in loop:
            inputs = batch[0].to(device)
            labels = batch[1].to(device)
            val_pred = net(inputs)

            batch_loss = error(val_pred,labels.long())
            
            loop.set_description(f"Validation {epoch+1}")
            try:
                auc = roc_auc_score(labels.cpu().numpy(), np.argmax(val_pred.cpu().data.numpy(), axis=1))     # use AUC-ROC metric if different class are represented
                val_metric = np.append(val_metric, auc)
            except:
                val_metric = np.append(val_metric, np.sum(np.argmax(val_pred.cpu().data.numpy(),axis=1) == labels.cpu().numpy()) / BATCH_SIZE)        # else use Accuracy metric
            val_loss = np.append(val_loss, loss.item())
            loop.set_postfix(loss=np.mean(val_loss), AUC_ROC=np.mean(val_metric))

Epoch 1:   1%|          | 3/541 [00:01<04:10,  2.15it/s, AUC_ROC=0.5, loss=40.9]

[0 0 0 0] [1 1 1 1]


Epoch 1:   1%|▏         | 8/541 [00:03<03:38,  2.44it/s, AUC_ROC=0.5, loss=22]  

[1 1 1 1] [0 0 0 0]


Epoch 1:   2%|▏         | 9/541 [00:03<03:37,  2.45it/s, AUC_ROC=0.5, loss=19.7]

[1 1 1 1] [0 0 1 1]


Epoch 1:   3%|▎         | 15/541 [00:06<03:33,  2.47it/s, AUC_ROC=0.5, loss=14.5]

[1 1 1 1] [0 1 0 0]


Epoch 1:   4%|▎         | 19/541 [00:08<03:31,  2.46it/s, AUC_ROC=0.518, loss=11.9]

[0 1 0 1] [1 1 1 1]


Epoch 1:   6%|▌         | 30/541 [00:12<03:26,  2.48it/s, AUC_ROC=0.549, loss=7.89]

[0 0 0 0] [1 1 1 1]


Epoch 1:   6%|▌         | 33/541 [00:13<03:25,  2.48it/s, AUC_ROC=0.545, loss=7.27]

[1 1 1 1] [0 1 0 0]


Epoch 1:   7%|▋         | 37/541 [00:15<03:25,  2.45it/s, AUC_ROC=0.557, loss=6.57]

[0 0 0 0] [0 1 1 1]


Epoch 1:   8%|▊         | 41/541 [00:17<03:41,  2.26it/s, AUC_ROC=0.539, loss=6.01]

[0 0 0 0] [1 0 0 0]


Epoch 1:   9%|▉         | 49/541 [00:20<03:20,  2.45it/s, AUC_ROC=0.532, loss=5.2] 

[1 1 1 1] [1 1 1 1]


Epoch 1:  12%|█▏        | 67/541 [00:27<03:03,  2.58it/s, AUC_ROC=0.554, loss=4]   

[0 0 0 0] [0 0 0 0]


Epoch 1:  13%|█▎        | 73/541 [00:29<03:01,  2.58it/s, AUC_ROC=0.541, loss=3.74]

[1 1 1 1] [1 1 0 0]


Epoch 1:  14%|█▎        | 74/541 [00:30<03:00,  2.58it/s, AUC_ROC=0.541, loss=3.7] 

[1 1 1 1] [1 1 1 1]


Epoch 1:  16%|█▌        | 85/541 [00:34<02:57,  2.57it/s, AUC_ROC=0.532, loss=3.31]

[1 1 1 1] [1 1 1 0]


Epoch 1:  16%|█▋        | 89/541 [00:35<02:53,  2.60it/s, AUC_ROC=0.536, loss=3.19]

[1 1 1 1] [1 1 1 1]


Epoch 1:  18%|█▊        | 98/541 [00:39<02:50,  2.60it/s, AUC_ROC=0.532, loss=2.96]

[0 0 0 0] [0 0 1 1]


Epoch 1:  19%|█▉        | 105/541 [00:42<02:48,  2.59it/s, AUC_ROC=0.515, loss=2.83]

[1 1 1 1] [0 0 0 0]


Epoch 1:  21%|██        | 111/541 [00:44<02:45,  2.59it/s, AUC_ROC=0.509, loss=2.71]

[1 1 1 1] [1 1 1 1]


Epoch 1:  21%|██▏       | 116/541 [00:46<02:45,  2.57it/s, AUC_ROC=0.509, loss=2.63]

[0 0 0 0] [1 1 1 1]


Epoch 1:  24%|██▍       | 130/541 [00:51<02:44,  2.50it/s, AUC_ROC=0.512, loss=2.43]

[0 0 0 0] [1 1 1 1]


Epoch 1:  26%|██▌       | 138/541 [00:55<02:42,  2.49it/s, AUC_ROC=0.514, loss=2.33]

[0 0 0 0] [1 0 0 0]


Epoch 1:  27%|██▋       | 146/541 [00:58<02:32,  2.59it/s, AUC_ROC=0.513, loss=2.24]

[0 0 0 0] [0 0 0 0]


Epoch 1:  31%|███       | 169/541 [01:07<02:24,  2.58it/s, AUC_ROC=0.519, loss=2.04]

[0 0 0 0] [0 0 0 0]


Epoch 1:  35%|███▍      | 187/541 [01:14<02:16,  2.59it/s, AUC_ROC=0.518, loss=1.92]

[1 1 1 1] [0 0 0 0]


Epoch 1:  36%|███▌      | 193/541 [01:16<02:21,  2.46it/s, AUC_ROC=0.519, loss=1.88]

[0 0 0 0] [1 0 1 1]


Epoch 1:  36%|███▌      | 196/541 [01:17<02:21,  2.44it/s, AUC_ROC=0.521, loss=1.86]

[1 1 1 1] [0 0 0 0]


Epoch 1:  38%|███▊      | 208/541 [01:22<02:08,  2.59it/s, AUC_ROC=0.518, loss=1.8] 

[1 1 1 1] [0 0 1 1]


Epoch 1:  40%|███▉      | 216/541 [01:25<02:05,  2.59it/s, AUC_ROC=0.516, loss=1.76]

[0 0 0 0] [0 1 0 1]


Epoch 1:  42%|████▏     | 228/541 [01:30<02:01,  2.58it/s, AUC_ROC=0.519, loss=1.71]

[0 0 0 0] [0 1 0 0]


Epoch 1:  47%|████▋     | 256/541 [01:41<01:49,  2.59it/s, AUC_ROC=0.516, loss=1.6] 

[1 1 1 1] [0 0 0 0]


Epoch 1:  50%|█████     | 273/541 [01:47<01:45,  2.54it/s, AUC_ROC=0.515, loss=1.54]

[1 1 1 1] [0 1 0 0]


Epoch 1:  52%|█████▏    | 281/541 [01:50<01:40,  2.59it/s, AUC_ROC=0.516, loss=1.52]

[1 1 1 1] [0 0 0 1]


Epoch 1:  52%|█████▏    | 284/541 [01:52<01:40,  2.56it/s, AUC_ROC=0.516, loss=1.51]

[1 1 1 1] [0 0 0 0]


Epoch 1:  54%|█████▍    | 292/541 [01:55<01:36,  2.59it/s, AUC_ROC=0.516, loss=1.49]

[0 0 0 0] [0 0 0 0]


Epoch 1:  55%|█████▍    | 296/541 [01:56<01:34,  2.60it/s, AUC_ROC=0.516, loss=1.48]

[1 1 1 1] [0 0 0 0]


Epoch 1:  58%|█████▊    | 312/541 [02:03<01:33,  2.44it/s, AUC_ROC=0.513, loss=1.44]

[0 0 0 0] [0 0 0 0]


Epoch 1:  58%|█████▊    | 314/541 [02:04<01:33,  2.44it/s, AUC_ROC=0.513, loss=1.43]

[0 0 0 0] [0 0 0 0]


Epoch 1:  59%|█████▉    | 318/541 [02:05<01:27,  2.54it/s, AUC_ROC=0.513, loss=1.43]

[1 1 1 1] [0 0 0 0]


Epoch 1:  62%|██████▏   | 338/541 [02:13<01:24,  2.40it/s, AUC_ROC=0.512, loss=1.38]

[0 0 0 0] [0 0 0 0]


Epoch 1:  64%|██████▍   | 347/541 [02:17<01:20,  2.42it/s, AUC_ROC=0.513, loss=1.36]

[0 0 0 0] [0 0 0 0]


Epoch 1:  65%|██████▍   | 349/541 [02:18<01:17,  2.47it/s, AUC_ROC=0.515, loss=1.36]

[1 1 1 1] [0 1 1 0]


Epoch 1:  67%|██████▋   | 364/541 [02:24<01:09,  2.56it/s, AUC_ROC=0.515, loss=1.33]

[0 0 0 0] [1 0 0 0]


Epoch 1:  67%|██████▋   | 365/541 [02:24<01:08,  2.56it/s, AUC_ROC=0.515, loss=1.33]

[1 1 1 1] [0 0 0 0]


Epoch 1:  68%|██████▊   | 369/541 [02:26<01:06,  2.57it/s, AUC_ROC=0.514, loss=1.32]

[1 1 1 1] [0 0 0 0]


Epoch 1:  69%|██████▉   | 372/541 [02:27<01:06,  2.54it/s, AUC_ROC=0.514, loss=1.32]

[1 1 1 1] [0 0 0 0]


Epoch 1:  69%|██████▉   | 375/541 [02:28<01:07,  2.47it/s, AUC_ROC=0.516, loss=1.31]

[1 1 1 1] [0 0 1 0]


Epoch 1:  72%|███████▏  | 389/541 [02:34<01:00,  2.49it/s, AUC_ROC=0.515, loss=1.29]

[1 1 1 1] [0 0 0 0]


Epoch 1:  74%|███████▍  | 401/541 [02:39<00:55,  2.51it/s, AUC_ROC=0.514, loss=1.28]

[1 1 1 1] [0 0 0 0]


Epoch 1:  75%|███████▌  | 406/541 [02:40<00:52,  2.55it/s, AUC_ROC=0.514, loss=1.27]

[0 0 0 0] [0 0 0 0]


Epoch 1:  78%|███████▊  | 420/541 [02:46<00:46,  2.60it/s, AUC_ROC=0.514, loss=1.25]

[1 1 1 1] [0 0 0 0]


Epoch 1:  78%|███████▊  | 424/541 [02:47<00:44,  2.60it/s, AUC_ROC=0.513, loss=1.24]

[0 0 0 0] [0 0 0 0]


Epoch 1:  79%|███████▉  | 428/541 [02:49<00:43,  2.60it/s, AUC_ROC=0.513, loss=1.24]

[0 0 0 0] [0 0 0 0]


Epoch 1:  82%|████████▏ | 445/541 [02:55<00:37,  2.57it/s, AUC_ROC=0.512, loss=1.22]

[1 1 1 1] [0 0 0 0]


Epoch 1:  83%|████████▎ | 450/541 [02:57<00:36,  2.52it/s, AUC_ROC=0.512, loss=1.21]

[1 1 1 1] [1 1 1 1]


Epoch 1:  84%|████████▎ | 452/541 [02:58<00:34,  2.55it/s, AUC_ROC=0.512, loss=1.21]

[0 0 0 0] [1 1 1 1]


Epoch 1:  84%|████████▎ | 453/541 [02:59<00:34,  2.55it/s, AUC_ROC=0.512, loss=1.21]

[1 1 1 1] [1 1 1 1]


Epoch 1:  84%|████████▍ | 454/541 [02:59<00:34,  2.53it/s, AUC_ROC=0.512, loss=1.21]

[0 0 0 0] [1 1 1 1]


Epoch 1:  86%|████████▌ | 466/541 [03:04<00:29,  2.56it/s, AUC_ROC=0.511, loss=1.2] 

In [ ]:
torch.save(net.state_dict(), rf"model lr{LR} e{EPOCHS}.pt")

In [ ]:
net.load_state_dict(torch.load("model lr0.001 e15.pt"))


In [ ]:
from torch.autograd import Variable
from PIL import Image

def predict_image(image_path, model, device):
    image = Image.open(image_path)

    transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))]
    )

    image_tensor = transform(image).float()
    image_tensor = image_tensor.unsqueeze(0)

    if torch.cuda.is_available() and device == "cuda":
        image_tensor.cuda()
        input = Variable(image_tensor.cuda(), requires_grad=True) #torch.Tensor(image_tensor.cuda(), requires_grad=True)
    else:
        input = Variable(image_tensor.cuda(), requires_grad=True) #torch.Tensor(image_tensor.cuda(), requires_grad=True)
    output = model(input)
    #label = output.data.cpu().numpy()
    label = torch.nn.functional.softmax(output.data.cpu())
    label = label.numpy()
    
    return label[0][0].round(1)
    #plt.imshow(image)


In [ ]:
predict_image(r"C:\Users\PC\Desktop\Проги\ML\Задание на стажировку\test\test\zvavwunqimpeqmiahuxd.jpg", net, device)

In [ ]:
path = r"test\test"
test_imgs = []
for file in os.listdir(path):
    test_imgs.append({'filename': file})
df_test = pd.DataFrame(test_imgs)
print("Test images: ", len(df_test))

In [ ]:
blurness = []
for file in os.listdir(path):
    blurness.append(predict_image(os.path.join(path, file), net, device))


In [ ]:
blurness

In [ ]:
df_test['blur'] = blurness
df_test['filename'] = df_test['filename'].apply(lambda x : os.path.split(x)[1])
df_test.to_csv('submission 2.csv', index=False)